# Generated by Django 4.1.4 on 2023-01-02 06:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allergies_food',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='allergies_medications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='allergies_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='barangay',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('NA', 'No Answer')], default='NA', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='civil_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widow'), ('O', 'Others')], default='S', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='emergencyContact_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='family_history',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HT', 'Hypertension'), ('C', 'Cancer'), ('KD', 'Kidney Disease'), ('DM', 'Diabetes Mellitus'), ('HD', 'Heart Disease'), ('TD', 'Thyroid Disease'), ('S', 'Stroke'), ('BA', 'Bronchial Asthma'), ('O', 'Other Disease'), ('NA', 'None')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hospitalization_medical_history',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='other_medical_history',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='past_medical_history',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HT', 'Hypertension'), ('C', 'Cancer'), ('HP', 'Hospitalization'), ('KD', 'Kidney Disease'), ('DM', 'Diabetes Mellitus'), ('HD', 'Heart Disease'), ('TD', 'Thyroid Disease'), ('SO', 'Surgical Operation'), ('S', 'Stroke'), ('BA', 'Bronchial Asthma'), ('O', 'Other Disease'), ('NA', 'None')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='surgical_operation_medical_history',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
