# Generated by Django 4.1.4 on 2023-01-02 06:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_student_allergies_food_student_allergies_medications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('complaint_id', models.CharField(max_length=20, unique=True)),
                ('chief_complain', models.CharField(blank=True, max_length=500)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('illness_period', models.CharField(blank=True, max_length=500)),
                ('medications', models.CharField(blank=True, max_length=500)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(default=datetime.datetime.now)),
                ('assessment_status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=50)),
                ('initial_diagnosis_status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=50)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.nurse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.student')),
            ],
        ),
    ]
