# Generated by Django 4.1.4 on 2023-01-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='assessment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('not needed', 'Not Needed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='initial_diagnosis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('not needed', 'Not Needed')], default='pending', max_length=50),
        ),
    ]
