# Generated by Django 4.1.4 on 2023-01-02 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_student_allergies_food_student_allergies_medications_and_more'),
        ('complaints', '0002_alter_complaint_assessment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('symptoms', models.CharField(max_length=1000)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_assigned', models.DateTimeField(default=datetime.datetime.now)),
                ('assessment_status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('not needed', 'Not Needed')], default='pending', max_length=50)),
                ('initial_diagnosis_status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('not needed', 'Not Needed')], default='pending', max_length=50)),
                ('for_initial_diagnosis', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=50)),
                ('final_prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('lr_prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('rf_prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('gb_prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('final_prediction_similar_diseases', models.CharField(blank=True, max_length=500, null=True)),
                ('lr_prediction_similar_diseases', models.CharField(blank=True, max_length=500, null=True)),
                ('rf_prediction_similar_diseases', models.CharField(blank=True, max_length=500, null=True)),
                ('gb_prediction_similar_diseases', models.CharField(blank=True, max_length=500, null=True)),
                ('final_prediction_treatment', models.CharField(blank=True, max_length=500, null=True)),
                ('lr_prediction_treatment', models.CharField(blank=True, max_length=500, null=True)),
                ('rf_prediction_treatment', models.CharField(blank=True, max_length=500, null=True)),
                ('gb_prediction_treatment', models.CharField(blank=True, max_length=500, null=True)),
                ('final_prediction_description', models.CharField(blank=True, max_length=500, null=True)),
                ('lr_prediction_description', models.CharField(blank=True, max_length=500, null=True)),
                ('rf_prediction_description', models.CharField(blank=True, max_length=500, null=True)),
                ('gb_prediction_description', models.CharField(blank=True, max_length=500, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor')),
                ('assigned_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.nurse')),
                ('complaint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='complaints.complaint')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.student')),
            ],
        ),
    ]
